spring.application.name=camel-project
camel.springboot.main-run-controller=true
management.endpoints.web.exposure.include=health,info,prometheus
# Endpoint Security (HTTPS)
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=ENC(EHsAahqv9n3o87pVBlU57Q==)
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=camel-broker-project
server.ssl.enabled-protocols=TLSv1.3,TLSv1.2

app.crypto.aes-key-hex=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
app.crypto.aes-iv-hex=00112233445566778899aabbccddeeff

jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

